[package]
name = "aws-iam"
version = "0.1.0"
authors = ["Simon Johnston <johnstonskj@gmail.com>"]
edition = "2018"
description = "A Rust crate for dealing with the actual Policy files themselves"
repository = "https://github.com/johnstonskj/aws-iam-model.git"
readme = "README.md"
default-run = "policy"

[[bin]]
name = "policy"
path = "src/bin/policy.rs"
required-features = ["command-line"]

[features]
command-line = ["structopt",  "env_logger"]

[dependencies]
uuid = { version = "0.8", features = ["serde", "v4"] }
lazy_static = "1.4.0"
log = { version = "0.4", features = ["std"] }
regex = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Command-Line feature dependencies
structopt = { optional = true, version = "0.3.3" }
env_logger = { optional = true, version = "0.7.1" }

[dev-dependencies]
test-generator = "0.3.0"