[package]
name = "aws-iam"
version = "0.2.1"
authors = ["Simon Johnston <johnstonskj@gmail.com>"]
edition = "2018"
description = "A Rust crate for dealing with AWS IAM Policy resources"
documentation = "https://docs.rs/aws-iam/"
repository = "https://github.com/johnstonskj/rust-aws-iam.git"
license = "MIT"
readme = "README.md"
publish = true
default-run = "policy"

[[bin]]
name = "policy"
path = "src/bin/policy.rs"
required-features = ["command-line"]

[features]
command_line = ["structopt",  "env_logger"]
offline_eval = []
service_config = ["toml"]

[dependencies]
uuid = { version = "0.8", features = ["serde", "v4"] }
lazy_static = "1.4.0"
log = { version = "0.4", features = ["std"] }
regex = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Command-Line feature dependencies
structopt = { optional = true, version = "0.3.3" }
env_logger = { optional = true, version = "0.7.1" }

# Service Config feature dependencies
toml = { optional = true, version = "0.5" }

[dev-dependencies]
test-generator = "0.3.0"