[package]
name = "aws-iam"
version = "0.1.0"
authors = ["Simon Johnston <johnstonskj@gmail.com>"]
edition = "2018"
description = "A Rust crate for dealing with the actual Policy files themselves"
repository = "https://github.com/johnstonskj/aws-iam-model.git"
readme = "README.md"

[dependencies]
lazy_static = "1.4.0"
regex = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
